#!/opt/maths/bin/perl
use strict;
use warnings;
use lib 'lib';
use Totient;

=head1 totient

Show each x: phi(x) = n.

=cut

my($n) = @ARGV;
my @t = Totient::totient($n);
print @t ? "@t\n" : "none\n";
exit 0;
