#!/opt/maths/bin/perl
use strict;
use warnings;
use Math::GMP;
use lib 'lib';
use Totient;

=head1 totient

Show each x: phi(x) = n.

=cut

my($n) = map Math::GMP->new($_), @ARGV;
my @t = Totient::totient($n);
print @t ? "@t\n" : "none\n";
exit 0;
