#!/opt/maths/bin/perl
use strict;
use warnings;

use Graph;
use lib 'lib';
use Graph::Hamilton;

my $g = Graph::Undirected->new;
for my $i (2..7) {
    my $sq = $i * $i;
    for my $j (1 .. 32) {
        my $k = $sq - $j;
        last if $k <= $j;
        next if $k > 32;
        $g->add_edge($j, $k);
    }
}
print Graph::Hamilton->findBFF($g);

