#!/opt/maths/bin/perl
use strict;
use warnings;

use Graph;
use lib 'lib';
use Graph::Hamilton;

my $g = Graph::Undirected->new;
for my $i (2..12) {
    my $qu = $i * $i * $i * $i;
    for my $j (1 .. 9641) {
        my $k = $qu - $j;
        last if $k <= $j;
        next if $k > 9641;
        $g->add_edge($j, $k);
    }
}
print Graph::Hamilton->findB($g);

